apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-pr
spec:
  serviceAccountName: tekton-triggers-golang-service-account
  triggers:
  - name: github-listener
    interceptors:
    - github:
        secretRef:
          secretName: github-trigger-secret
          secretKey: secretToken
        eventTypes:
        - push
    - cel:
        filter: "body.ref == 'refs/heads/main'"
    bindings:
      - ref: github-pr-binding ##Name of PR Binding
    template:
        ref: github-pr-pipeline-template