apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.serviceName }}
    spec:
      containers:
      - image: {{ .Values.containerRepo }}:{{ .Values.containerImage }}
        ports:
        - containerPort: 8000
        name: backend-service
        resources: {}
        env:
        - name: PORT
          value: 8000
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-database-credentials
              key: db_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-database-credentials
              key: db_password
        - name: MY_CONFIG
          valueFrom:
            configMapKeyRef:
              name: my-sample-config
              key: config
status: {}
