apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backendgolang
  name: backendgolang
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backendgolang
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backendgolang
    spec:
      containers:
      - image: {{ .Values.containerImage }}
        ports:
        - containerPort: 8000
        name: backend-service
        resources: {}
        env:
        - name: SAMPLE_VARIABLE
          value: sample
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: pwd
        - name: MY_CONFIG
          valueFrom:
            configMapKeyRef:
              name: my-sample-config
              key: config
status: {}
