apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-stable
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: psbonline-stable.development.ns1.civo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: {{ .Values.serviceName  | quote}}
          servicePort: 8000

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-canary
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: psbonline-canary.development.ns1.civo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          # Reference to a Service name, also specified in the Rollout spec.strategy.canary.stableService field
          serviceName: {{ .Values.serviceNameCanary  | quote}}
          servicePort: 8000