apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-stable
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: rollouts-gobackend
    http:
      paths:
      - path: /election2022
        backend:
          serviceName: {{ .Values.serviceName  | quote}}
          servicePort: 8080

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-canary
  annotations:
    kubernetes.io/ingress.class: traefik
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "5"
spec:
  rules:
  - host: rollouts-gobackend-canary
    http:
      paths:
      - path: /
        backend:
          # Reference to a Service name, also specified in the Rollout spec.strategy.canary.stableService field
          serviceName: {{ .Values.serviceNameCanary  | quote}}
          servicePort: 8080