apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backendgolang
    app.kubernetes.io/managed-by: Helm
  name: backendgolang
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backendgolang
  type: LoadBalancer
status:
  loadBalancer: {}
