apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.serviceName  | quote}}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.serviceName  | quote}}
  namespace: {{ .Values.namespace  | quote}}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.serviceName  | quote}}
  type: ClusterIP
status:
  loadBalancer: {}
