apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang-task-three-go-build
spec:
  params:
    - name: CGO_ENABLED
      default: "0"
    - name: FLAGS
      default: -v
    - name: GOOS
      default: linux
    - name: DEST_FOLDER
      description: destination of main.go
      default: './cmd/main'

  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: run-build
      image: golang:alpine
      workingDir: /GolangBackend
      script: |
        cd /workspace/repo
        go env
        go build -o $(params.DEST_FOLDER) $(params.DEST_FOLDER)
      env:
        - name: CGO_ENABLED
          value: "$(params.CGO_ENABLED)"
        - name: GOOS
          value: "$(params.GOOS)"
