# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: atlas-ing-stable
#   annotations:
#     kubernetes.io/ingress.class: traefik
#     traefik.ingress.kubernetes.io/router.entrypoints: web
# spec:
#   rules:
#   - host: {{ .Values.ingressStable  | quote}}
#     http:
#       paths:
#       - path: /atlas
#         backend:
#           serviceName: {{ .Values.serviceNameCanary  | quote}}
#           servicePort: 8080

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: atlas-ing-new
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: {{ .Values.ingressCanary  | quote}}
    http:
      paths:
      - path: /atlas
        backend:
          # Reference to a Service name, also specified in the Rollout spec.strategy.canary.stableService field
          serviceName: {{ .Values.serviceNameCanary  | quote}}
          servicePort: 8080