apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.appName  | quote}}
  name: atlas-rollout
  namespace: {{ .Values.namespace  | quote}}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: {{ .Values.appName  | quote}}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.appName  | quote}}
    spec:
      # imagePullSecrets:
      #   - name: regcred
      containers:
      - image: {{ .Values.repo }}/{{ .Values.image }}:{{.Chart.AppVersion}}
        ports:
        - containerPort: {{ .Values.containerPort }}
        imagePullSecrets:
        - name: regcred
        name: backend-service
        resources: {}
        env:
        - name: PORT
          value: {{ .Values.containerPort | quote}}
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      canaryService: {{ .Values.serviceNew  | quote}}
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 1m # 1 minute
      - setWeight: 20
      - pause: {} # pause indefinitely
      # blueGreen:
      #    autoPromotionEnabled: false
      #    activeService: {{ .Values.serviceStable  | quote}}
      #    previewService: {{ .Values.serviceNew  | quote}}
