apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang-task-two-docker-build-push
spec:
  params:
    - name: IMAGE_TAG
      default: "mysqlgolang10"
    - name: IMAGE_REPO
      default: "arrelpoblete/backend-service"
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.3.0
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      command:
        - /kaniko/executor
        - --dockerfile=Dockerfile
        - --context=/workspace/repo
        - --destination=$(params.IMAGE_REPO):$(params.IMAGE_TAG)