# Default values for GoBackend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
serviceStable: atlas-svc-stable
namespace: development
repo: registry.psbulap.com
image: development
replica: 4
containerPort: 8000
serviceNew: atlas-svc-new
ingressStable: stable-development.cicd.psbulap.com
ingressNew: new-development.cicd.psbulap.com
appName: atlas